<?php /* Smarty version 2.6.26, created on 2015-10-22 18:46:01
         compiled from employer/index.tpl */ ?>
<?php require_once(SMARTY_CORE_DIR . 'core.load_plugins.php');
smarty_core_load_plugins(array('plugins' => array(array('function', 'lang', 'employer/index.tpl', 2, false),)), $this); ?>
<?php echo '<?xml'; ?>
 version="1.0" encoding="<?php echo smarty_function_lang(array('mkey' => 'ENCODING'), $this);?>
"<?php echo '?>'; ?>

<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=<?php echo smarty_function_lang(array('mkey' => 'ENCODING'), $this);?>
" />
<?php echo '<title>'; ?><?php echo $this->_tpl_vars['html_title']; ?><?php echo '</title><meta name="description" content="'; ?><?php echo $this->_tpl_vars['meta_description']; ?><?php echo '" /><meta name="keywords" content="'; ?><?php echo $this->_tpl_vars['meta_keywords']; ?><?php echo '" /><link href="'; ?><?php echo $this->_tpl_vars['css_path']; ?><?php echo '/employer/main.css" type="text/css" media="screen" rel="stylesheet"/><link href="'; ?><?php echo $this->_tpl_vars['css_path']; ?><?php echo '/menu_style.css" type="text/css" media="screen" rel="stylesheet"/>'; ?><?php echo $this->_tpl_vars['extra_styelSheet']; ?><?php echo '<script language="javascript" type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['HCJQUERYPATH']; ?><?php echo 'jquery-1.7.2.min.js"></script><script language="javascript" type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['DOC_ROOT']; ?><?php echo 'javascript/tiny_mce/tiny_mce.js"></script><script language="javascript" type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['DOC_ROOT']; ?><?php echo 'javascript/java.js"></script><script language="javascript" type="text/javascript" src="'; ?><?php echo $this->_tpl_vars['DOC_ROOT']; ?><?php echo 'javascript/cascade.js"></script><script type="text/javascript" >var loadingTag = "'; ?><?php echo smarty_function_lang(array('mkey' => 'loading'), $this);?><?php echo '";var url = "'; ?><?php echo $this->_tpl_vars['BASE_URL']; ?><?php echo '";</script></head><body dir="'; ?><?php echo smarty_function_lang(array('mkey' => 'DIRECTION'), $this);?><?php echo '"><table border="0" cellspacing="0" cellpadding="0" width="100%" id="main_table">'; ?><?php echo '<tr><td><table width="100%">'; ?><?php if ($this->_tpl_vars['dont_include_left'] == '' && ! $this->_tpl_vars['dont_include_left']): ?><?php echo '<colgroup><col class="left_col" /><col class="right_col" /></colgroup><tr><td valign="top" width="20%">'; ?><?php echo $this->_tpl_vars['left_side']; ?><?php echo '</td>'; ?><?php else: ?><?php echo '<tr>'; ?><?php endif; ?><?php echo '<td valign="top">'; ?><?php echo $this->_tpl_vars['rendered_page']; ?><?php echo '</td></tr></table></td></tr>'; ?><?php echo '</table>'; ?><?php echo ''; ?><?php echo '</body></html>'; ?>